-- Equipment inspections module
create table if not exists public.equipment_inspections(
 id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references public.profiles(id),report_number text not null unique,equipment_type text not null,equipment_name text,asset_id text,manufacturer text,model text,serial_number text,location text not null,inspection_at timestamptz not null default now(),inspector_name text not null,inspector_role text,competent_person boolean not null default false,checklist jsonb not null default '[]'::jsonb,defects_found text,corrective_action text,assigned_to text,due_date date,overall_status text not null check(overall_status in ('approved','corrective_action','remove_from_service')),removed_from_service boolean not null default false,tag_applied boolean not null default false,comments text,osha_reference text,status text not null default 'draft' check(status in ('draft','final','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.equipment_inspection_photos(id uuid primary key default gen_random_uuid(),inspection_id uuid not null references public.equipment_inspections(id) on delete cascade,path text not null unique,caption text,uploaded_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create index if not exists equipment_inspections_project_id_idx on public.equipment_inspections(project_id);create index if not exists equipment_inspections_created_by_idx on public.equipment_inspections(created_by);create index if not exists equipment_inspection_photos_inspection_id_idx on public.equipment_inspection_photos(inspection_id);create index if not exists equipment_inspection_photos_uploaded_by_idx on public.equipment_inspection_photos(uploaded_by);
alter table public.equipment_inspections enable row level security;alter table public.equipment_inspection_photos enable row level security;
revoke all on public.equipment_inspections,public.equipment_inspection_photos from anon,authenticated;grant select,insert,update,delete on public.equipment_inspections to authenticated;grant select,insert,delete on public.equipment_inspection_photos to authenticated;
create policy "equipment inspections project view" on public.equipment_inspections for select to authenticated using(private.is_project_member(project_id));
create policy "safety creates equipment inspections" on public.equipment_inspections for insert to authenticated with check(created_by=(select auth.uid()) and private.is_project_member(project_id) and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','safety_director','safety','supervisor')));
create policy "safety updates equipment inspections" on public.equipment_inspections for update to authenticated using(private.is_project_member(project_id) and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','safety_director','safety'))) with check(private.is_project_member(project_id) and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role in ('admin','safety_director','safety')));
create policy "creator deletes failed equipment draft" on public.equipment_inspections for delete to authenticated using(created_by=(select auth.uid()) and status='draft');
create policy "equipment inspection photos view" on public.equipment_inspection_photos for select to authenticated using(exists(select 1 from public.equipment_inspections i where i.id=inspection_id and private.is_project_member(i.project_id)));
create policy "equipment inspection photos insert" on public.equipment_inspection_photos for insert to authenticated with check(uploaded_by=(select auth.uid()) and exists(select 1 from public.equipment_inspections i where i.id=inspection_id and i.created_by=(select auth.uid())));
create policy "equipment inspection photos delete own" on public.equipment_inspection_photos for delete to authenticated using(uploaded_by=(select auth.uid()));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('equipment-inspections','equipment-inspections',false,10485760,array['image/jpeg','image/png','image/webp','image/heic','image/heif']) on conflict(id) do nothing;
create policy "equipment inspection evidence view" on storage.objects for select to authenticated using(bucket_id='equipment-inspections' and exists(select 1 from public.equipment_inspection_photos p join public.equipment_inspections i on i.id=p.inspection_id where p.path=storage.objects.name and private.is_project_member(i.project_id)));
create policy "equipment inspection evidence upload" on storage.objects for insert to authenticated with check(bucket_id='equipment-inspections' and exists(select 1 from public.equipment_inspections i where i.id=(split_part(storage.objects.name,'/',1))::uuid and i.created_by=(select auth.uid())));
create policy "equipment inspection evidence delete own" on storage.objects for delete to authenticated using(bucket_id='equipment-inspections' and owner_id=((select auth.uid()))::text);
