-- Team multi-channel notifications
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists notify_email boolean not null default true;
alter table public.profiles add column if not exists notify_sms boolean not null default true;
alter table public.profiles add column if not exists notify_app boolean not null default true;
create table if not exists public.notification_deliveries(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,event_type text not null check(event_type in ('observation_digest','correction_digest','incident_alert')),channel text not null check(channel in ('app','email','sms')),reference_id uuid,status text not null default 'pending' check(status in ('pending','sent','failed','skipped')),provider text,provider_message_id text,error_message text,scheduled_for timestamptz not null default now(),sent_at timestamptz,created_at timestamptz not null default now());
create index if not exists notification_deliveries_project_idx on public.notification_deliveries(project_id);create index if not exists notification_deliveries_user_idx on public.notification_deliveries(user_id);create index if not exists notification_deliveries_due_idx on public.notification_deliveries(status,scheduled_for);
alter table public.notification_deliveries enable row level security;revoke all on public.notification_deliveries from anon,authenticated;grant select on public.notification_deliveries to authenticated;
create policy "users view own notification deliveries" on public.notification_deliveries for select to authenticated using(user_id=(select auth.uid()));
create or replace function private.queue_project_notification(p_project uuid,p_event text,p_reference uuid,p_immediate boolean default false) returns void language plpgsql security definer set search_path='' as $$ begin insert into public.notification_deliveries(project_id,user_id,event_type,channel,reference_id,status,scheduled_for) select p_project,pm.user_id,p_event,c.channel,p_reference,'pending',case when p_immediate then now() else date_trunc('hour',now())+interval '24 hours' end from public.project_members pm join public.profiles pr on pr.id=pm.user_id cross join lateral (values ('app',pr.notify_app),('email',pr.notify_email),('sms',pr.notify_sms)) c(channel,enabled) where pm.project_id=p_project and c.enabled and (c.channel<>'sms' or nullif(trim(pr.phone),'') is not null);end;$$;
revoke all on function private.queue_project_notification(uuid,text,uuid,boolean) from public,anon,authenticated;
create or replace function private.observation_notification_trigger() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='INSERT' then perform private.queue_project_notification(new.project_id,'observation_digest',new.id,false);elsif tg_op='UPDATE' and old.status is distinct from new.status then perform private.queue_project_notification(new.project_id,'correction_digest',new.id,false);end if;return new;end;$$;
revoke all on function private.observation_notification_trigger() from public,anon,authenticated;drop trigger if exists queue_observation_notifications on public.observations;create trigger queue_observation_notifications after insert or update of status on public.observations for each row execute function private.observation_notification_trigger();
create or replace function private.incident_notification_trigger() returns trigger language plpgsql security definer set search_path='' as $$ begin perform private.queue_project_notification(new.project_id,'incident_alert',new.id,true);return new;end;$$;
revoke all on function private.incident_notification_trigger() from public,anon,authenticated;drop trigger if exists queue_incident_notifications on public.incident_reports;create trigger queue_incident_notifications after insert on public.incident_reports for each row execute function private.incident_notification_trigger();