import {test} from 'node:test';
import assert from 'node:assert/strict';
import {orientationSnapshot,orientationEvidence,renderOrientationRecord,attachIncidentEmployee} from '../src/incident-employee.js';
import {renderIncidentReport} from '../src/incident-report-template.js';
const tr=en=>en,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const employee={id:'record',sticker_number:'GE42',employee_name:'Worker',employee_position:'Carpenter',employee_company:'G&E',orientation_date:'2026-09-20',notes:'<notes>',orientation_photo_path:'face',sticker_photo_path:'sticker',orientation_document_photo_path:'document',certificate_photo_paths:['cert1','cert2']};
test('orientation snapshots preserve registered data and reject malformed draft data',()=>{assert.equal(orientationSnapshot('{bad'),null);assert.equal(orientationSnapshot(null),null);const s=orientationSnapshot({...employee,extra:'ignored',certificate_photo_paths:['valid',null]});assert.equal(s.extra,undefined);assert.deepEqual(s.certificate_photo_paths,['valid']);assert.equal(s.employee_position,'Carpenter')});
test('all orientation evidence uses the existing protected orientation bucket',async()=>{const calls=[];const photos=await orientationEvidence(employee,async(bucket,path)=>{calls.push([bucket,path]);return 'blob:'+path},tr);assert.equal(photos.length,5);assert.ok(calls.every(([bucket])=>bucket==='orientation-photos'));assert.equal(photos[4].label,'Certificate 2')});
test('orientation information and evidence render safely within report people section',()=>{const html=renderIncidentReport({employee_orientation_snapshot:employee,incident_type:'injury'},[],{tr,esc,fmt:()=>'',employeePhotos:[{label:'Employee Face ID',url:'blob:face'}]});for(const text of ['GE42','Worker','Carpenter','2026-09-20','&lt;notes&gt;','blob:face'])assert.ok(html.includes(text),text);assert.ok(!html.includes('<notes>'));assert.ok(!renderOrientationRecord(employee,[],{tr,esc}).includes('undefined'))});
function field(value=''){return {value,listeners:{},addEventListener(type,fn){this.listeners[type]=fn},dispatchEvent(){}}}
function fixture(query){const fields=Object.fromEntries(['employee_sticker','employee_orientation_snapshot','employee_name','employee_job_title','employee_company'].map(k=>[k,field()]));const panel={},status={},button={},details={},list={append(){}},listeners={};const form={elements:{namedItem:k=>fields[k]},querySelector:s=>({'[data-employee-record]':panel,'[data-employee-status]':status,'[data-employee-find]':button,'#incident-sticker-list':list,'.incident-employee-record':details}[s]),addEventListener(type,fn){listeners[type]=fn}};const db={from(){return {select(){return this},eq(){return this},order(){return this},range:async()=>({data:[]}),maybeSingle:query}}};attachIncidentEmployee(form,{db,tr,esc,sign:async(_,p)=>'blob:'+p,isCurrent:()=>true,onError(){}});return {fields,panel,status,button,details,listeners}}
test('selecting a sticker fills only orientation fields and stores its snapshot',async()=>{const f=fixture(async()=>({data:employee}));f.fields.employee_sticker.value=' ge42 ';await f.button.onclick();assert.equal(f.fields.employee_name.value,'Worker');assert.equal(f.fields.employee_job_title.value,'Carpenter');assert.equal(f.fields.employee_company.value,'G&E');assert.equal(JSON.parse(f.fields.employee_orientation_snapshot.value).sticker_number,'GE42');assert.ok(f.panel.innerHTML.includes('blob:cert2'));assert.equal(f.details.open,true);f.fields.employee_sticker.listeners.input();assert.equal(f.fields.employee_orientation_snapshot.value,'');assert.equal(f.fields.employee_name.value,'Worker')});
test('restored snapshots retain saved employee data without reading a changed Team record',async()=>{let reads=0;const f=fixture(async()=>{reads++;return {data:employee}});f.fields.employee_orientation_snapshot.value=JSON.stringify(employee);f.fields.employee_sticker.value='GE42';f.fields.employee_name.value='Edited report name';await f.button.onclick();assert.equal(reads,0);assert.equal(f.fields.employee_name.value,'Edited report name');assert.ok(f.panel.innerHTML.includes('Worker'))});
test('late lookup responses cannot replace a newly selected employee',async()=>{const resolvers=[];const f=fixture(()=>new Promise(resolve=>resolvers.push(resolve)));f.fields.employee_sticker.value='GE42';const first=f.button.onclick();f.fields.employee_sticker.value='GE43';const second=f.button.onclick();resolvers[1]({data:{...employee,sticker_number:'GE43',employee_name:'Second'}});await second;resolvers[0]({data:employee});await first;assert.equal(f.fields.employee_name.value,'Second');assert.equal(JSON.parse(f.fields.employee_orientation_snapshot.value).sticker_number,'GE43')});
test('pending lookup blocks premature submit; missing records retain manual fields',async()=>{let resolve;const f=fixture(()=>new Promise(r=>resolve=r));f.fields.employee_name.value='Manual';f.fields.employee_sticker.value='missing';const lookup=f.button.onclick();let blocked=false;f.listeners.submit({preventDefault(){blocked=true},stopImmediatePropagation(){}});assert.equal(blocked,true);resolve({data:null});await lookup;assert.equal(f.fields.employee_name.value,'Manual');assert.equal(f.fields.employee_orientation_snapshot.value,'');assert.match(f.status.textContent,/not found/)});
