import {test} from 'node:test';
import assert from 'node:assert/strict';
import {saveCloudToolbox} from '../server/toolbox-save.js';
import handler from '../api/toolbox-save.js';
const user={id:'419e77e4-0fe2-408a-99e9-968f945d176c'},project='331accb7-f57a-4ed7-ba7c-7e5c678479b7';
const record={id:'75bd28ff-29ef-41f7-b848-568fc17d3b4a',project_id:project,created_by:'spoofed',kind:'toolbox',report_number:'TB-VERIFY',payload:{topic:'Cloud report',approvals:{safety:{name:'Safety',strokes:[[[0.1,0.2],[0.4,0.5]]]}}}};
const photos=Array.from({length:6},(_,i)=>({path:`${user.id}/${project}/safety_tool_toolbox/default/photos/photo-${i}.jpeg`,name:`Photo ${i}`,type:'image/jpeg',size:2000000}));
function fixture(options={}){const copied=[],inserted=[];let confirmed=false;const db={from(){let row;const q={select(){return q},eq(){return q},maybeSingle(){return q},single(){return q},insert(value){row=value;return q},then(resolve,reject){if(row){inserted.push(row);confirmed=true;return Promise.resolve(options.lostResponse?{error:{message:'Lost response'}}:{data:{id:row.id}}).then(resolve,reject)}return Promise.resolve({data:options.existing||confirmed?{id:record.id}:null,error:null}).then(resolve,reject)}};return q},storage:{from(bucket){return {copy:async(source,target,opts)=>{copied.push({bucket,source,target,opts});return options.copyError?{error:options.copyError}:{data:{path:target}}}}}}};return {db,copied,inserted}}
test('six Toolbox photos copy cloud-to-cloud without bytes crossing the iPad and preserve signatures',async()=>{const t=fixture();const result=await saveCloudToolbox(t.db,user,{record,draftPhotos:photos});assert.equal(result.id,record.id);assert.equal(t.copied.length,6);assert.equal(t.inserted.length,1);assert.equal(t.inserted[0].created_by,user.id);assert.deepEqual(t.inserted[0].payload,record.payload);assert.deepEqual(t.inserted[0].photos.map(p=>p.label),photos.map(p=>p.name));assert.ok(t.copied.every(p=>p.bucket==='draft-evidence'&&p.opts.destinationBucket==='safety-tool-evidence'))});
test('already saved Toolbox record returns without copies or duplicate insertion',async()=>{const t=fixture({existing:true});await saveCloudToolbox(t.db,user,{record,draftPhotos:photos});assert.equal(t.copied.length,0);assert.equal(t.inserted.length,0)});
test('retry after a lost copy response uses stable paths and accepts an existing copy',async()=>{const a=fixture(),b=fixture({copyError:{message:'The resource already exists',statusCode:'409'}});await saveCloudToolbox(a.db,user,{record,draftPhotos:photos});await saveCloudToolbox(b.db,user,{record,draftPhotos:photos});assert.deepEqual(a.copied,b.copied);assert.equal(b.inserted.length,1)});
test('lost database response verifies the committed report',async()=>{const t=fixture({lostResponse:true});assert.equal((await saveCloudToolbox(t.db,user,{record,draftPhotos:photos})).id,record.id);assert.equal(t.inserted.length,1)});
test('other employee or jobsite draft paths are rejected before copying',async()=>{for(const path of [photos[0].path.replace(user.id,'another-user'),photos[0].path.replace(project,'another-project'),photos[0].path+'/nested',photos[0].path.replace('photo-0.jpeg','../bad')]){const t=fixture();await assert.rejects(saveCloudToolbox(t.db,user,{record,draftPhotos:[{...photos[0],path}]}),/Invalid draft evidence/);assert.equal(t.copied.length,0);assert.equal(t.inserted.length,0)}});
test('storage permission failure does not create a report or delete draft evidence',async()=>{const t=fixture({copyError:{message:'Permission denied',statusCode:'403'}});await assert.rejects(saveCloudToolbox(t.db,user,{record,draftPhotos:photos}),e=>e.message==='Permission denied');assert.equal(t.inserted.length,0)});
test('Toolbox endpoint requires POST and authentication',async()=>{for(const [req,status] of [[{method:'GET',headers:{}},405],[{method:'POST',headers:{}},401]]){let actual;const res={setHeader(){},status(value){actual=value;return res},json(value){return value}};await handler(req,res);assert.equal(actual,status)}});
